stages:
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG
  
before_script:
  - sudo -g docker docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  only:
    - master
  tags:
    - docker
  stage: build
  variables:
    REACT_APP_WEB_URL_PRODUCTION: "https://testpid.science.mcgill.ca:8443/tepid"
  script:
    - cat Dockerfile | envsubst | sudo -g docker docker build -t $CONTAINER_TEST_IMAGE -f- .
    - sudo -g docker docker push $CONTAINER_TEST_IMAGE

deploy testing:
  stage: deploy
  tags:
    - docker
  only:
    - dev
    - master
  before_script:
    - sudo -g docker docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $COMPOSE_DIR
    - sudo -g docker docker-compose up -d
